include:
  - board: nice_nano/v2
    shield: cygnus_left
  - board: nice_nano/v2
    shield: cygnus_right
  - board: nice_nano/v2
    shield: scotto63
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
